### ISSUE TITLE
It's not working like described

### ISSUE THREAD

**Issue by gander** [BjornTheProgrammer/bun-plugin-html#10]
```html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello World!</title>
</head>
<body>
<h1>Hello World</h1>
<p id="js-target">This should be changed by JS</p>
<script src="main.ts"></script>
</body>
```

```ts
import html from 'bun-plugin-html';

await Bun.build({
    entrypoints: ['./src/index.html'],
    outdir: './dist',
    plugins: [
        html()
    ],
});
```

```json
{
  "compilerOptions": {
    "lib": ["ESNext"],
    "target": "ESNext",
    "module": "ESNext",
    "moduleDetection": "force",
    "jsx": "react-jsx",
    "allowJs": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "verbatimModuleSyntax": true,
    "noEmit": true,

    /* Linting */
    "strict": true,
    "skipLibCheck": true,
    "noFallthroughCasesInSwitch": true,
  }
}
```

```shell
bun build ./src/index.ts --outdir ./dist
```

in `dist` result file is `index.js` with something:

```js
// node_modules/bun-plugin-html/dist/index.js
var {createRequire: Mb} = (()=>({}));
var { default: aG} = (()=>({}));

//// lots of js

// src/index.ts
await Bun.build({
  entrypoints: ["./src/index.html"],
  outdir: "./dist",
  plugins: [
    zD0()
  ]
});
```

**Comment by BjornTheProgrammer** [comment]
Hello @gander,

The issue is that you must run the file that contains the `Bun.build` function call, not the `bun build` command itself. Instead of running the command `bun build ./src/index.ts --outdir ./dist` run the command `bun run ./src/index.ts`, and it should work as intended. Also, I recommend reading the [bun's docs](https://bun.sh/docs/bundler#plugins) for further details on how the bundler works. 

### What does this command do?
`bun build ./src/index.ts --outdir ./dist`
This command for the bundler is the equivalent of this function in Typescript
```ts
await Bun.build({
    entrypoints: ['./src/index.html'],
    outdir: './dist',
});
```

**Comment by gander** [comment]
Yes, I tried to find an answer in the documentation on how I should run the code containing `Bun.build()`, but I couldn't find a clear answer and `bun run ./src/index.ts` wasn't generating anything, so I finally asked the AI in the documentation about it. I literally asked what CLI command I should use to run the code containing `Bun.build()` and it replied that `bun build ./index.tsx --outdir=./build`. 

I applied your code and now I actually get the result as expected. I don't understand at all why it didn't work for me before. I must have done something wrong, but now I can't repeat it to learn from my mistake.
